image_src_rows: 256
image_src_cols: 256
image_src_chns: 3
image_tgt_rows: 256
image_tgt_cols: 256
image_tgt_chns: 3
discriminator_conv_layers: 3
discriminator_first_conv_filters: 64
generator_downsamplings: 8
generator_first_conv_filters: 64
norm_layer: batch
use_dropout: true
init_type: normal
init_gain: 0.02
loss: vanilla  # vanilla, wgangp
lr: 0.0002
beta1: 0.5
beta2: 0.999
lambda_l1: 100
batch_size: 1
epochs: 200