image_rows: 256
image_cols: 256
image_chns: 3
discriminator_conv_layers: 3
discriminator_first_conv_filters: 64
generator_downsamplings: 8
generator_first_conv_filters: 64
norm_layer: batch
use_dropout: true
init_type: normal
init_gain: 0.02
loss: wgangp  # vanilla, wgangp
dg_train_ratio: 5  # train how many times of discriminator before train generator once
lr: 0.0002
beta1: 0.5
beta2: 0.999
lambda_l1: 100
lambda_gp: 10  # used for wgangp loss only
batch_size: 4
epochs: 200
val_freq: 1
save_freq: 20